### ISSUE TITLE
Edge arrow size does not apply to new edges

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#303]
Changing edge arrow size option affects the current edges, however newly added edges do not use the new arrow size value.

**Comment by ugurdogrusoz** [comment]
@leonarddrv Is this resolved now?

**Comment by leonarddrv** [comment]
@ugurdogrusoz  Not yet. There is still a bug when converting into a reversible reaction.

**Comment by hasanbalci** [comment]
I think it still does not work on edges added from template.

**Comment by ugurdogrusoz** [comment]
Let's not worry about this for 1.1

**Comment by hasanbalci** [comment]
Edges added from template seem ok now, but when we clone or copy a reaction, newly created edges still do not use the new arrow size value.

**Comment by hasanbalci** [comment]
I know it becomes annoying but there is one more case where edge arrow size does not apply to some edges. For example, if there exists a collapsed node that includes an edge and we change the arrow size, then when we expand that node, edge arrows do not use the new arrow size value.

**Comment by ugurdogrusoz** [comment]
Isn't there a more central way of doing this rather than case by case I wonder

**Comment by ugurdogrusoz** [comment]
OK, we're going to have to resolve problems on a case by case basis then.

**Comment by ugurdogrusoz** [comment]
@leonarddrv This seems fixed, thanks. But I want to make sure we do this cleanly. I think we should apply the new arrow size as soon as arrow size is changed. That is, we should apply the new arrow size both on hidden and collapsed edges as well.

**Comment by ugurdogrusoz** [comment]
@hasanbalci please verify that it's resolved

**Comment by hasanbalci** [comment]
It seems ok now, thanks!
