### ISSUE TITLE
Refine/fix import/export operations

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/newt#712]
Current export menu is implemented for exporting SBGNML maps to other formats such as SBML, SIF etc. and they should be working well. However, when we added other formats, SIF and SBML, we didn't put any restrictions for users to use export functionality for these types and this currently leads to wrong export operations. For example, user is able to export SBML file to SBGNML but not in the proper way. The output file of this conversion leads to an SBGNML file with map type SBML which is inconvenient. As a solution we need to add support for possible conversions and disable the rest with a warning message.

[Minerva](https://minerva.pages.uni.lu/doc/api/16.1/converter.html) converter that we are currently using for some format conversions supports conversion of SBML to SBGN, GPML and CellDesigner. So we can add support for these three conversions (For SBML -> SBGN conversion, we need to check to which SBGNML version Minerva converts). I think, SBML to SIF conversion can be implemented manually. 

Other conversions, SIF to all other formats and if there is any from SBML, we need to show a warning to the user that the export is not currently possible.

**Comment by ugurdogrusoz** [comment]
To properly understand the current situation, I prepared some tables [here](https://docs.google.com/spreadsheets/d/18bzRmwWOK2O3bz4TvuZZtypzpAO5Mx3rOARYmsk0Iw8/edit?usp=sharing).

**Comment by hasanbalci** [comment]
One problem I noticed is the following: Before SBML support, when we try to export SBGN maps as SBML, we were using MINERVA service. After the SBML support, we have write functionality for SBML maps and current 'Export as SBML' button uses that functionality. However, when an SBGN map is open in the canvas and if we try to export the map SBML, the app behaves like the current map is SBML and tries to write it with the write functionality provided with SBML support. Instead it should use Minerva converter instead to convert the current SBGN map to SBML.

**Comment by ugurdogrusoz** [comment]
After having discussed all varying combinations, here is what needs to change according to [this document](https://docs.google.com/spreadsheets/d/18bzRmwWOK2O3bz4TvuZZtypzpAO5Mx3rOARYmsk0Iw8/edit?usp=sharing):
- [ ] 1. Where we see "NA" in export table entries, let's popup a dialog (similar style to existing ones), that says "Not applicable for the current map type!"
- [ ] 2.

**Comment by okg21** [comment]
For item 2, I encountered two types of problem when using minerva service for PD to SBML conversion.

1. For some PD samples sbgnml to sbml minerva conversion returns an xml with this note inside:
```
[Complex:glyph15]	Unknown extension: extraInfo
[Complex:glyph11]	Unknown extension: extraInfo
[glyph32_0:state]	Invalid structural state
[Complex:glyph14]	Unknown extension: extraInfo
[Complex:glyph12]	Unknown extension: extraInfo
[Complex:glyph13]	Unknown extension: extraInfo
[Complex:glyph18]	Unknown extension: extraInfo
[Complex:glyph16]	Unknown extension: extraInfo</p>
```

2. For some PD samples Minerva returns an Internal Server Error.  For instance when I try to export PD sample Drosophilia Cell Cycle as SBML, I get the following error:
```
error: "Internal server error."
error-id: "0a5fb699-3739-42cf-a5f9-a5779b367de1"
reason: "[Complex 89360553-bab4-532a-c6c7-624272c4e43b]\tProblem with exporting bioEntity"
```

**Comment by okg21** [comment]
Regarding item 3, I pushed some fixes to sbgnviz for the SBML map to .sbml export. https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/2cc6ec68b6a865d0172ed0099d2d19185a40abac
Below are the pre-fix and post-fix exports for the SBML mapped Pharmacokinetics sample.
Before fix:
![Screenshot 2024-07-04 at 17 10 52](https://github.com/iVis-at-Bilkent/newt/assets/24496613/3dbc9f2e-1a1d-49a1-b4f4-2c08c278560a)
After fix:
![Screenshot 2024-07-04 at 17 07 46](https://github.com/iVis-at-Bilkent/newt/assets/24496613/c4c7cfec-5c4f-458d-8051-9aadf3be8257)

**Comment by okg21** [comment]
As of now, items 1, 3 and 6 should be working properly.

**Comment by ugurdogrusoz** [comment]
1: is OK now
3: SBML -export-to-> SBML: still missing layout info, SBML -export-to-> CellDesigner: conversion service is not available
6: is OK now

**Comment by umut-er** [comment]
With regards to number 5: The service we are using to make apparently has some limitations. If you start with an sbgnml file, convert it to a cd file and try to convert it back using the same service, it won't work. We get the following error message every time:

```zsh
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.sbml._2001.ns.celldesigner.ListOfLayers.getLayer()" because the return value of "org.sbml._2001.ns.celldesigner.ModelAnnotationType$Extension.getListOfLayers()" is null
        at fr.curie.cd2sbgnml.xmlcdwrappers.ModelWrapper.addBasicLists(ModelWrapper.java:105)
        at fr.curie.cd2sbgnml.xmlcdwrappers.ModelWrapper.create(ModelWrapper.java:62)
        at fr.curie.cd2sbgnml.CD2SBGNML.toSbgn(CD2SBGNML.java:53)
        at fr.curie.cd2sbgnml.CD2SBGNML.convert(CD2SBGNML.java:857)
        at fr.curie.cd2sbgnml.Cd2SbgnmlScript.convert(Cd2SbgnmlScript.java:48)
```

However, if you use the samples provided with the web service, such as [these](https://drive.google.com/drive/folders/17yfFg8V9VI3eiyCI0wcoQs_3tmi0cApB?usp=drive_link), you can see that you can successfully import these. Export seems to work fine as well right now.

**Comment by ugurdogrusoz** [comment]
@umut-er based on your findings, I checked 5.

**Comment by hasanbalci** [comment]
Perhaps due to the changes related to item 3, now when we export SMBL Model as .sbml, spinner starts but doesn't stops.

**Comment by umut-er** [comment]
> Perhaps due to the changes related to item 3, now when we export SBML Model as .sbml, spinner starts but doesn't stop.

Should be fixed now.

**Comment by hasanbalci** [comment]
> > Perhaps due to the changes related to item 3, now when we export SBML Model as .sbml, spinner starts but doesn't stop.
> 
> Should be fixed in the next regular build.

@umut-er I think you didn't build the sbgnviz repo before pushing the change.

**Comment by umut-er** [comment]
I have been working on the layout information issue. This is a status update. Apparently there is already an sbml extension for encoding layouts (you can find a very detailed explanation of it [here](https://www.degruyter.com/document/doi/10.1515/jib-2015-267/html), which we probably should cite as per [this](https://sbml.org/documents/specifications/level-3/version-1/layout/)). libsbmljs already implements this behavior. Using that functionality, I have added some layout information (this is by no means done yet):
The map:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/0601c068-f58a-4846-9440-b4dde913f716">

Old Export:
```html
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns="http://www.sbml.org/sbml/level2/version4" level="2" version="4">
  <model id="model1">
    <listOfSpecies>
      <species sboTerm="SBO:0000252" id="nwtN_09271ecb_560d_47af_9933_cb85352049e0"/>
      <species sboTerm="SBO:0000252" id="nwtN_738b4f4f_240f_4f06_ac73_d0623379d89e"/>
    </listOfSpecies>
  </model>
</sbml>
```

New Export:
```html
<?xml version="1.0" encoding="UTF-8"?>
<sbml xmlns="http://www.sbml.org/sbml/level2/version4" level="2" version="4">
  <model id="model1">
    <annotation>
      <layout:listOfLayouts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:layout="http://projects.eml.org/bcb/sbml/level2">
        <layout:layout layout:id="layout_1">
          <layout:dimensions layout:width="274.25" layout:height="141.25"/>
          <layout:listOfSpeciesGlyphs>
            <layout:speciesGlyph layout:species="nwtN_68b25e79_9748_4924_97b7_7c04d1fc6c7c">
              <layout:boundingBox>
                <layout:position layout:x="476.375" layout:y="335.375"/>
                <layout:dimensions layout:width="63.25" layout:height="33.25"/>
              </layout:boundingBox>
            </layout:speciesGlyph>
            <layout:speciesGlyph layout:species="nwtN_f1e0f887_a4c0_41e0_b891_dd57f109b574">
              <layout:boundingBox>
                <layout:position layout:x="687.375" layout:y="227.375"/>
                <layout:dimensions layout:width="63.25" layout:height="33.25"/>
              </layout:boundingBox>
            </layout:speciesGlyph>
          </layout:listOfSpeciesGlyphs>
        </layout:layout>
      </layout:listOfLayouts>
    </annotation>
    <listOfSpecies>
      <species sboTerm="SBO:0000252" id="nwtN_68b25e79_9748_4924_97b7_7c04d1fc6c7c"/>
      <species sboTerm="SBO:0000252" id="nwtN_f1e0f887_a4c0_41e0_b891_dd57f109b574"/>
    </listOfSpecies>
  </model>
</sbml>
```

Once this is done, we can move on to reading this format of layout (libsbmljs also has functionality to help with that). Our current import functionality cannot read this new file at all (not just the layout information).

PS. This is not up on the internal server. It is too early to push and breaks the import functionality.

PS 2. Is there another web service or something similar that can read .sbml files with layout information? It would be good to test the new export since our import is currently unable to handle this.

**Comment by umut-er** [comment]
Also, I the celldesigner app neither exports nor imports files with layout information (at least the version I have of the app). If you are using that export functionality, you wouldn't be able to test these features.

**Comment by umut-er** [comment]
Please drag & drop this celldesigner file after renaming it to testing.xml: 
[testing.txt](https://github.com/user-attachments/files/16350562/testing.txt)
There is a console error. Might be related to the changes here.

**Comment by ugurdogrusoz** [comment]
> Please drag & drop this celldesigner file after renaming it to testing.xml: [testing.txt](https://github.com/user-attachments/files/16350562/testing.txt) There is a console error. Might be related to the changes here.

Probably because we currently **require** "nwt:" namespace present in the file. This will be made optional.

**Comment by okg21** [comment]
> > Please drag & drop this celldesigner file after renaming it to testing.xml: [testing.txt](https://github.com/user-attachments/files/16350562/testing.txt) There is a console error. Might be related to the changes here.
> 
> Probably because we currently **require** "nwt:" namespace present in the file. This will be made optional.

I implemented the support for this. 'nwt' namespace is no longer required.

**Comment by umut-er** [comment]
@okg21 and I spoke about this issue and decided to split the task. I am responsible for the export and @okg21 will do the import.

Import feature is coming along nicely. Couple of things:
1. Logic Operations: These are almost impossible to export. MINERVA doesn't export it either. You can test it by building a map including logic with PD and trying to export -> import it in SBML. I think the best thing to do in that case is alerting the user that the map can't be exported if it includes logical arcs.
2. Bezier / Bending Curves: We don't currently have support for this. The layout package can only support up to cubic Bezier curves.
3. Reduced arcs: These are not done yet. I am working on it. I don't expect any issues here.

**Comment by ugurdogrusoz** [comment]
> Export feature is coming along nicely. Couple of things:
> 
> 1. Logic Operations: These are almost impossible to export. MINERVA doesn't export it either. You can test it by building a map including logic with PD and trying to export -> import it in SBML. I think the best thing to do in that case is alerting the user that the map can't be exported if it includes logical arcs.

Can we simply ignore them? Export without them.

> 2. Bezier / Bending Curves: We don't currently have support for this. The layout package can only support up to cubic Bezier curves. Bend support can probably be implemented.

Let's ignore Bezier information, as if it's a straight line.

> 3. Reduced arcs: These are not done yet. I am working on it. I don't expect any issues here.

OK

**Comment by umut-er** [comment]
The layout export code is now pushed to github and should be live on the internal server shortly. 
> Can we simply ignore them? Export without them.

We should be doing that now.

The association / dissociation layout is ignored for now.

**Comment by okg21** [comment]
I pushed a preliminary patch for .sbml import. Currently I recognized process node's positions are calculated wrong. There may be other issues. I will be testing with more samples. Below I exported a SBML mapped sample with native .sbml export and then imported back.
Original SBML mapped sample.
![image](https://github.com/user-attachments/assets/858633f8-e5b7-40a4-ae2c-128c4e8f3539)
Exported to .sbml and then imported again:
![image](https://github.com/user-attachments/assets/6359a652-ea08-441c-84a9-a0cc44c69adb)

**Comment by okg21** [comment]
@ugurdogrusoz We can close item 2b. Both nwt: and and 'nwt'less are supported for reading currently.

**Comment by umut-er** [comment]
For the SBML export operation, if the map we are trying to export is invalid (see example below), the program will get stuck on a spinner with an error on the console. We should alert the user instead.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/9c578604-b22e-490a-beb2-e2b870d37448">

This is the second SBML sample, which is invalid because of the indicated process node (maybe we should fix this sample as well). If you try to export this, you will see the problem.

**Comment by hasanbalci** [comment]
I think the original version of that sample is [here](https://www.ebi.ac.uk/biomodels/search?query=pharmacokinetics+of+PFOA+and+PFOS+in+the+monkey&domain=biomodels). When we open it as SBGN, there is a node is connected to that process, but I don't know whether it exist in the file or Minerva adds it to make it valid.
![Screenshot 2024-07-31 at 12 18 46](https://github.com/user-attachments/assets/8d41f9bf-3f5d-49b9-872a-54b5df0704f4)

**Comment by umut-er** [comment]
Except an issue with the compartment layout (can be seen with sbml sample 2), the layout functionality is almost done for both export and import (can be seen with all other sbml samples except 2).

**Comment by hasanbalci** [comment]
Currently, I cannot import this SBML file [SBML_Sample.sbml.txt](https://github.com/user-attachments/files/16474513/SBML_Sample.sbml.txt) with layout extension. It might be because of :nwt namespacing. Can you please check?

**Comment by umut-er** [comment]
> Currently, I cannot import this SBML file [SBML_Sample.sbml.txt](https://github.com/user-attachments/files/16474513/SBML_Sample.sbml.txt) with layout extension. It might be because of :nwt namespacing. Can you please check?

It should be fixed now. Can you please confirm the import (both nodes and layout) is correct? If you have an image of the map, I can also check.

**Comment by hasanbalci** [comment]
I see two issues in the import of this file:
- The first issue is actually a general issue for complex nodes in SBML. Complex nodes are container nodes, but as far as I know SBML format doesn't keep parent reference on the child nodes of the complex nodes. So we need to infer nesting ourselves based on the bounding box of the complex nodes. So if a simple node falls into the bounding box of a complex then we should set the complex as the parent of simple node. The image of the actual map is the following except the boundaries of the complex (The layout algorithm I generated the image includes labels in node dimensions, so normally complexes should tightly wrap their children): 
![SBML_Sample](https://github.com/user-attachments/assets/1e23e068-3b1b-4a63-985d-30f97fe20bf9)
- The second issue is the sizes of process nodes. Why do we have different node sizes for the process nodes such as 10,06x10,06, 10,73x10,73 and 10,25x10,25?

**Comment by umut-er** [comment]
For the second issue: Process node positioning and size is a difficult issue in the SBML format. In our export operation, the way we define layout for processes is with a line segment from the input port to the output port. The following is from the [SBML Layout Package Specifications](https://www.degruyter.com/document/doi/10.1515/jib-2015-267/html)
> TheCurvedescribes the center section of aReactionGlyph. The center section is frequently used by tools to sep-19arate the point where substrates arcs come together, from the point where product arcs split off.

Probably because the image you provided has no ports, the exported file produced a bunch of line segments whose function is not entirely clear. Here is one:
```xml
<layout:curve>
  <layout:listOfCurveSegments>
    <layout:curveSegment xsi:type="LineSegment">
      <layout:start layout:x="1089.5413818359375" layout:y="939.7005615234375" layout:z="0"/>
      <layout:end layout:x="1093.6632724157312" layout:y="929.4532789670211" layout:z="0"/>
    </layout:curveSegment>
    <layout:curveSegment xsi:type="LineSegment">
      <layout:start layout:x="1093.6632724157312" layout:y="929.4532789670211" layout:z="0"/>
      <layout:end layout:x="1113.1137767048137" layout:y="926.0207775620547" layout:z="0"/>
    </layout:curveSegment>
  </layout:listOfCurveSegments>
</layout:curve>
```
this seems to define something like this (the red and blue lines):
<img width="350" alt="image" src="https://github.com/user-attachments/assets/6b598561-002e-473e-8072-ebfdddd34153">

However, we currently do not read information like this. We always assume there are ports in the input and try to read one single line like this:
<img width="280" alt="image" src="https://github.com/user-attachments/assets/9731d609-c6b9-46ae-a2ec-c9d8d91095df">

The code tries to read information on that map in this way. This explains the different node sizes. This also explains why the process nodes are very small, it takes the line segment to the middle as the entire size of the process node. 

We can try to import and export processes without ports as well but that hasn't been implemented yet.

**Comment by hasanbalci** [comment]
@umut-er Ok, then please ignore the second issue.

**Comment by ugurdogrusoz** [comment]
> * The first issue is actually a general issue for complex nodes in SBML. Complex nodes are container nodes, but as far as I know SBML format doesn't keep parent reference on the child nodes of the complex nodes. So we need to infer nesting ourselves based on the bounding box of the complex nodes. So if a simple node falls into the bounding box of a complex then we should set the complex as the parent of simple node. The image of the actual map is the following except the boundaries of the complex (The layout algorithm I generated the image includes labels in node dimensions, so normally complexes should tightly wrap their children):

Regarding this, we should **infer** nesting as @hasanbalci suggests only when the corresponding user setting is **Infer Nesting on Load** is true. There should already be some code for other notations that *could be* reused.

**Comment by umut-er** [comment]
@hasanbalci I don't think we do infer nesting on load for complexes in PD. Should we do infer nesting for complexes in SBML? If yes, should we infer nesting for both compartments and complexes? That can cause some weird cases since compartments inside complexes are not allowed. But it should be possible. Alternatively, we can do infer nesting for only complexes since we are unlikely to encounter improperly nested compartments in SBML files.

**Comment by umut-er** [comment]
I also pushed some changes to sbgnviz in the above commit. We now import the file @hasanbalci provided above like this:

<img width="717" alt="image" src="https://github.com/user-attachments/assets/87e26492-d7f8-46fe-ae99-dbe33b97ec61">

this map is now ready for infer nesting.

**Comment by ugurdogrusoz** [comment]
if containment / parent relations are not defined in a file and we will infer the nesting on load, then we do this by simply looking at the geometry of simple and container nodes. So, if a simple node (e.g., a protein) is inside a complex, which is in turn inside a compartment, then inference should never yield any invalid situations, assuming the geometry of the complex and the compartment are proper. So, if SBML maps seem to not contain parent-child relations defined as part of .sbml files for complexes and complex members, then I suggest we do the following: 
- initially start with all simple nodes as children node C
- for each node in C, 
    o find all container nodes (compartment, complex or submap) that this node is inside and is a potential parent (complex cannot be a parent of a compartment for instance), and among them make the innermost container node the parent of this node
    o delete the node from C and add the parent node to C
- repeat above until no more inference can be made

**Comment by umut-er** [comment]
In SBML, every node must have a compartment defined or the file is invalid. This is also what we do. If every node doesn't have a compartment, we make up a default compartment in the exported file. Note that we don't render the default compartment in the import process. That's why implementing infer nesting on load for compartments for SBML files makes less sense than for other formats (since parent relationships are always going to be defined for valid SBML files). But we can infer nesting for complexes. I am currently working on that.

**Comment by ugurdogrusoz** [comment]
@umut-er The issue is not just reading a file without a problem. It's also about fixing certain commonly made mistakes by users. Inferring compartments is needed simply because users ignore to say this protein is in this compartment even though they draw it inside that compartment. So, we should ideally apply inference to all container types. I don't know why we ignored complexes in SBGN PD (probably because users did specify owner complexes but neglected compartments).

**Comment by hasanbalci** [comment]
I had an effort to infer nesting during sbml to json conversion, if it helps: https://github.com/iVis-at-Bilkent/syblars/blob/main/src/sbml-to-cytoscape.js

**Comment by umut-er** [comment]
> I had an effort to infer nesting during sbml to json conversion, if it helps: https://github.com/iVis-at-Bilkent/syblars/blob/main/src/sbml-to-cytoscape.js

It was very helpful. I implemented something very similar to this. I think the file you provided works now. Please check it after the server rebuilds.

**Comment by umut-er** [comment]
I will summarize the issues left here since I was asked about it yesterday:
1. There is an issue with the ports being reversed after export -> import if the file is handcrafted in the app. This does not happen with external files. 
2. Association / dissociation import / export is not functional.
3. If the underlying map is invalid when we try to export, the app stops with an error message in the console. We should just show a screen with a message like `Export is not possible. The most common cause is the map being invalid`.

**Comment by umut-er** [comment]
The first issue in the above summary is addressed. Also, we are now able to export and import all of our SBML samples correctly, including the second one.

For number 2, I will suggest removing the process node in the association / dissociation and make it like it is in PD. Here are the SBML and the PD association / dissociation.


<img width="518" alt="image" src="https://github.com/user-attachments/assets/019bb046-9efd-4139-8410-fde8ff2c4fb7"> 
<img width="417" alt="image" src="https://github.com/user-attachments/assets/5629a078-9b3f-4ced-8555-0244d850571f">


One potential concern is that this would affect our compatibility with cell designer files. However, since there are no process nodes in SBML notation and that those are added by specific software packages, we will be preserving our present compatibilities (We will just have a slightly different way of expressing an association / dissociation reaction than celldesigner, fully consistent with SBML).
There are advantages to the single process node association / dissociation. First of all, their layout is more simply exported (it will be like all other process nodes). It will also be more simply understood by other software packages. It is also more consistent with our other notations. Also, in our code, the rules for connections will make more sense. For example, currently, we can have a consumption edge coming out of a process node (see SBML dissociation above). It will be overall more simple and easier to extend (like we are trying to do at #740).

I will be addressing item 3 next, waiting on what you think about my suggestion on number 2. I can answer questions related to that if you happen to have any.

**Comment by umut-er** [comment]
Item 3 is also ready for review (after server rebuild ~30 mins later). You can try to change the map file to SBML and then put a single process node (with no connections) and try to export for testing.
Some sort of SBML validation service might also be useful in the future to help users debug what it is that is invalid. I think we have something like that for PD maps.

**Comment by hasanbalci** [comment]
@umut-er For item 2, we can continue as you suggested. But if it will cause problem while importing the cell designer files, is it possible to convert CD style to the style you suggested while reading those files?

**Comment by hasanbalci** [comment]
@umut-er For item 3, we should allow user to export a map even if it is invalid. Because a user might be curating a map and want to save it anytime to continue later. We allow exporting invalid maps in other formats as well.

**Comment by umut-er** [comment]
> @umut-er For item 2, we can continue as you suggested. But if it will cause problem while importing the cell designer files, is it possible to convert CD style to the style you suggested while reading those files?

I realized that the converter we use for CD files converts them to SBGNML, not SBML. So, the changes we make to the SBML format has nothing to do with whether we are able to import CD files at all. Am I misunderstanding this?

Below is a CD file I just created in the CellDesigner app with a simple association reaction (Just remove the .txt. We can import this directly with drag & drop. The map type is PD after import).
[association.xml.txt](https://github.com/user-attachments/files/16512498/association.xml.txt)

> @umut-er For item 3, we should allow user to export a map even if it is invalid. Because a user might be curating a map and want to save it anytime to continue later. We allow exporting invalid maps in other formats as well.

Just to be clear, I was only talking about when the map includes reaction nodes with no inputs or outputs . I previously thought libsbmljs did not allow this but I checked and it appears I was wrong. I will implement that.

**Comment by hasanbalci** [comment]
@umut-er Yes, CD converter should be for CD to SBGN conversion. Currently, we cannot import any CD files with SBML import, right? We are expecting to use the CD -> SBGN converter. If this is the case, then there is no problem.

For item 3, please implement it, thanks!

**Comment by umut-er** [comment]
I think we should we good to go on item 2 and 3.

**Comment by umut-er** [comment]
I think we can tick 3 and 4 from [this](https://github.com/iVis-at-Bilkent/newt/issues/712#issuecomment-2197203564). There are no issues left there that I know of. 

Also, I would appreciate a brief explanation on the issues left with item 2 on that list. I have never worked on it and I am not very familiar with it.

**Comment by hasanbalci** [comment]
In item 2, we want to make sure that we are using Mınerva conversion service during export of PD maps as SBML and during import of SBML maps as PD. For the first operation, we should be using [this code](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/sbgnml-to-sbml-converter-factory.js) and for the second operation [this code](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/sbml-to-sbgnml-converter-factory.js) (you can see the API calls to Minerva service).
@umut-er Please make sure that we are using these codes and mentioned import and export operations work correctly.

**Comment by umut-er** [comment]
@hasanbalci can you check item 2 now? There was a small issue with the SBML -> .sbgn conversion but it should be fixed now.

**Comment by hasanbalci** [comment]
> In item 2, we want to make sure that we are using Mınerva conversion service during export of PD maps as SBML and during import of SBML maps as PD. For the first operation, we should be using [this code](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/sbgnml-to-sbml-converter-factory.js) and for the second operation [this code](https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/sbml-to-sbgnml-converter-factory.js) (you can see the API calls to Minerva service). @umut-er Please make sure that we are using these codes and mentioned import and export operations work correctly.

@umut-er I now realized that my explanation here for item 2 is not exactly correct, sorry. We want to make sure that the export from PD to SBML and export from SBML to PD are using Minerva converter. 

When testing I realized that while exporting an SBML map as SBGN-ML Plain or SBGN-ML Plain 0.3, Save dialog box remains open after we click on Save button. In addition, I don't remember if this is discussed before but can we add a spinner while exporting a PD map as SBML.

**Comment by umut-er** [comment]
Did you rebuild the server? I didn't @hasanbalci

**Comment by hasanbalci** [comment]
@umut-er Hmm, ok. I will test it after rebuild. But one last small request related to this issue: Can we make inferNestingOnLoad automatically true during import of SBML files. I think it is more natural to load it by inferring nesting, otherwise the user will have to remember and check the option every time.

**Comment by umut-er** [comment]
> @umut-er Hmm, ok. I will test it after rebuild. But one last small request related to this issue: Can we make inferNestingOnLoad automatically true during import of SBML files. I think it is more natural to load it by inferring nesting, otherwise the user will have to remember and check the option every time.

Ok, but I have some questions. Infer nesting on load is a variable of a map, not a format. So, if infer nesting is automatically true, 1) there would be no way to disable it for SBML, or, 2) it would be true by default for every format. Is that OK?

**Comment by hasanbalci** [comment]
If there is no way to define complex nodes as parents in SBML format, I think we should always apply it. Its disabled state is for using parent reference if it is already defined in the map, but if we are sure that there will be no such information, there is no need to disable it. 

Let's make this only for SBML, not for every format. You can keep the current option before loading the file, make it true temporarily, and then set it back to the current option. We do it while loading query results from PathwayCommons query as well.

**Comment by umut-er** [comment]
I made it so that we infer nesting on load for SBML files always if there is layout information. Naturally, we can't infer nesting if there is no layout information.

**Comment by hasanbalci** [comment]
@umut-er Everything looks good, thanks! Only I cannot see spinner while exporting a PD map as SBML. If we can also add it, I think we can close this issue.

**Comment by hasanbalci** [comment]
I also noticed that if I try to connect two macromolecules with a consumption edge (without a process in between), the error dialog box says "Conversion failed!". It was "Invalid edge type! Refer to Legend menu for help." before.

**Comment by umut-er** [comment]
Both issues are now fixed on the internal server.

**Comment by hasanbalci** [comment]
@umut-er Thanks, both issues are now ok. 
I think the import/export functionality is now in a pretty good state.

**Comment by ugurdogrusoz** [comment]
Issues with testing export/import will be separately reported, closing this issue.
